management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露
  endpoint:
    health:
      show-details: always
info:
  appName: bootAdmin
  mavenProjectName: spring-boot-web5


spring:
  profiles:
    active: