server:
  port: 80
spring:
  application:
    name: cloud-cousumer-order80
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT
    username: root
    password: root

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    #service-url:
      #defaultZone: http://localhost:7001/eureka
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
